# Generated by Django 5.0.2 on 2025-12-09 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=15)),
                ('Description', models.TextField(max_length=400)),
                ('Strength', models.IntegerField()),
                ('Charisma', models.IntegerField()),
                ('Intelligence', models.IntegerField()),
                ('Wisdom', models.IntegerField()),
                ('Dexterity', models.IntegerField()),
                ('Grit', models.IntegerField()),
                ('Overall', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=30)),
                ('FirstName', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=15)),
                ('Description', models.TextField(max_length=400)),
                ('Strength', models.IntegerField()),
                ('Charisma', models.IntegerField()),
                ('Intelligence', models.IntegerField()),
                ('Wisdom', models.IntegerField()),
                ('Dexterity', models.IntegerField()),
                ('Grit', models.IntegerField()),
                ('Overall', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winCondition', models.CharField(choices=[('S', 'Strength'), ('C', 'Charisma'), ('I', 'Intelligence'), ('W', 'Wisdom'), ('D', 'Dexterity'), ('G', 'Grit')], max_length=1)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FriendlyPowerScaling.profile', unique=True)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FriendlyPowerScaling.profile', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FriendlyPowerScaling.profile', unique=True)),
                ('player10', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FriendlyPowerScaling.profile', unique=True)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FriendlyPowerScaling.profile', unique=True)),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FriendlyPowerScaling.profile', unique=True)),
                ('player4', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FriendlyPowerScaling.profile', unique=True)),
                ('player5', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FriendlyPowerScaling.profile', unique=True)),
                ('player6', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FriendlyPowerScaling.profile', unique=True)),
                ('player7', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FriendlyPowerScaling.profile', unique=True)),
                ('player8', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FriendlyPowerScaling.profile', unique=True)),
                ('player9', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FriendlyPowerScaling.profile', unique=True)),
            ],
        ),
    ]
